/**
 * ODRL items
 *
 * Copyright 2016 Open Permissions Platform Coalition
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const ID_PREFIX = "http://openpermissions.org/ns/id/";
const TEMP_ID_PREFIX="http://openpermissions.org/ns/temporary_id/";
const OP_PREFIX="http://openpermissions.org/ns/op/1.1/";
const ODRL_PREFIX="http://www.w3.org/ns/odrl/2/";
const OPEX_PREFIX="http://openpermissions.org/ns/opex/1.0/";
const DCTERM_PREFIX="http://purl.org/dc/terms/";

const actions = [
  [ODRL_PREFIX+'export', 'Export'],
  [ODRL_PREFIX+'display', 'Display'],
  [ODRL_PREFIX+'digitize', 'Digitize'],
  [ODRL_PREFIX+'copy', 'Copy'],
  [ODRL_PREFIX+'give', 'Give'],
  [ODRL_PREFIX+'obtainConsent', 'Obtain consent'],
  [ODRL_PREFIX+'archive', 'Archive'],
  [ODRL_PREFIX+'install', 'Install'],
  [ODRL_PREFIX+'reproduce', 'Reproduce'],
  [ODRL_PREFIX+'anonymize', 'Anonymize'],
  [ODRL_PREFIX+'distribute', 'Distribute'],
  [ODRL_PREFIX+'include', 'Include'],
  [ODRL_PREFIX+'share', 'Share'],
  [ODRL_PREFIX+'attachPolicy', 'Attach policy'],
  [ODRL_PREFIX+'write', 'Write'],
  [ODRL_PREFIX+'present', 'Present'],
  [ODRL_PREFIX+'compensate','Compensate'],
  [ODRL_PREFIX+'annotate', 'Annotate'],
  [ODRL_PREFIX+'secondaryUse', 'Secondary use'],
  [ODRL_PREFIX+'inform', 'Inform'],
  [ODRL_PREFIX+'lend', 'Lend'],
  [ODRL_PREFIX+'attachSource', 'Attach source'],
  [ODRL_PREFIX+'grantUse', 'Grant use'],
  [ODRL_PREFIX+'appendTo', 'Append to'],
  [ODRL_PREFIX+'print', 'Print'],
  [ODRL_PREFIX+'modify', 'Modify'],
  [ODRL_PREFIX+'read', 'Read'],
  [ODRL_PREFIX+'attribute', 'Attribute'],
  [ODRL_PREFIX+'ensureExclusivity', 'Ensure exclusivity'],
  [ODRL_PREFIX+'lease', 'Lease'],
  [ODRL_PREFIX+'transform', 'Transform'],
  [ODRL_PREFIX+'extractWord', 'Extract word'],
  [ODRL_PREFIX+'use', 'Use'],
  [ODRL_PREFIX+'sell', 'Sell'],
  [ODRL_PREFIX+'execute', 'Execute'],
  [ODRL_PREFIX+'play', 'Play'],
  [ODRL_PREFIX+'nextPolicy', 'Next policy'],
  [ODRL_PREFIX+'move', 'Move'],
  [ODRL_PREFIX+'commercialize', 'Commercialize'],
  [ODRL_PREFIX+'delete', 'Delete'],
  [ODRL_PREFIX+'append', 'Append'],
  [ODRL_PREFIX+'shareAlike', 'Share-alike'],
  [ODRL_PREFIX+'acceptTracking', 'Accept tracking'],
  [ODRL_PREFIX+'extractChar', 'Extract character'],
  [ODRL_PREFIX+'watermark', 'Watermark'],
  [ODRL_PREFIX+'reviewPolicy', 'Review policy'],
  [ODRL_PREFIX+'writeTo', 'Write to'],
  [ODRL_PREFIX+'aggregate', 'Aggregate'],
  [ODRL_PREFIX+'license', 'License'],
  [ODRL_PREFIX+'adHocShare', 'Ad-hoc sharing'],
  [ODRL_PREFIX+'derive', 'Derive'],
  [ODRL_PREFIX+'index', 'Index'],
  [ODRL_PREFIX+'concurrentUse', 'Concurrent use'],
  [ODRL_PREFIX+'extract', 'Extract'],
  [ODRL_PREFIX+'transfer', 'Transfer'],
  [ODRL_PREFIX+'preview', 'Preview'],
  [ODRL_PREFIX+'extractPage', 'Extract page'],
  [ODRL_PREFIX+'pay', 'Pay'],
  [ODRL_PREFIX+'translate', 'Translate'],
  [ODRL_PREFIX+'textToSpeech', 'Text-to-speech'],
  [OPEX_PREFIX+'postOnSocialNetwork', 'Post on Social Network']
];

const operators = [
	[ODRL_PREFIX+'eq', 'Equal to'],
  [ODRL_PREFIX+'gt', 'Greater than'],
  [ODRL_PREFIX+'gteq', 'Greater than or equal to'],
  [ODRL_PREFIX+'hasPart', 'Has part'],
  [ODRL_PREFIX+'isA', 'Is a'],
  [ODRL_PREFIX+'isAllOf', 'Is all of'],
  [ODRL_PREFIX+'isAnyOf', 'Is any of'],
  [ODRL_PREFIX+'isNoneOf', 'Is none of'],
  [ODRL_PREFIX+'isPartOf', 'Is part of'],
  [ODRL_PREFIX+'lt', 'Less than'],
  [ODRL_PREFIX+'lteq', 'Less than or equal to'],
  [ODRL_PREFIX+'neq', 'Not equal to']
];

const units = [
  ['http://cvx.iptc.org/iso4217a/GBP', 'GBP'],
  [OPEX_PREFIX+'pixel', 'Pixel'],
  [OPEX_PREFIX+'visitorsPerMonth', 'Visitors Per Month']
];


const constraints = [
  //['media', 'Media'],
  //['meteredTime','Metered Time', 'http://www.w3.org/2000/01/rdf-schema#Literal'],
  [ODRL_PREFIX+'dateTime','Date Time', 'datetime-input'],
  [ODRL_PREFIX+'absolutePosition', 'Absolute Position', 'integer-input'],
  //['virtualLocation', 'Virtual Location', 'None'],
  [ODRL_PREFIX+'spatial', 'Spatial', 'spatial-dropdown'],
  //['elapsedTime', 'Elapsed Time', 'http://www.w3.org/2000/01/rdf-schema#Literal'],
  //['timeInterval', 'Time Interval', 'http://www.w3.org/2000/01/rdf-schema#Literal'],
  [ODRL_PREFIX+'product', 'Product', 'text-input'],
  //['industry', 'Industry', 'None'],
  [ODRL_PREFIX+'percentage', 'Percentage', 'decimal-input'],
  //['resolution', 'Resolution', 'None'],
  //['purpose', 'Purpose', 'None'],
  //['fileFormat', 'File Format', 'None'],
  //['version', 'Version', 'None'],
  [ODRL_PREFIX+'count', 'Count', 'non-negative-integer-input'],
  [ODRL_PREFIX+'absoluteSize', 'Absolute Size', 'decimal-input'],
  //['systemDevice', 'System Device', 'None'],
  [ODRL_PREFIX+'payAmount', 'Pay Amount', 'decimal-input'],
  //['language', 'Language', 'None'],
  //['relativeSize', 'Relative Size', 'None'],
  //['relativePosition', 'Relative Position', 'None'],
  //['deliveryChannel', 'Delivery Channel', 'None'],
  //['event','Event', 'None'],
  //['recipient', 'Recipient', 'None'],
  [OPEX_PREFIX+'attributeText', 'AttributeText', 'text-input'],
  [OPEX_PREFIX+'views', 'Views', 'integer-input'],
  [OPEX_PREFIX+'height', 'Height', 'integer-input'],
  [OPEX_PREFIX+'width', 'Width', 'integer-input'],
  [OPEX_PREFIX+'post', 'Post', 'host-dropdown']
];

const spatial = [
  ['http://sws.geonames.org/6295630/', 'Earth'],
  ['http://sws.geonames.org/290557/', 'United Arab Emirates'],
  ['http://sws.geonames.org/1149361/', 'Afghanistan'],
  ['http://sws.geonames.org/3576396/', 'Antigua and Barbuda'],
  ['http://sws.geonames.org/3573511/', 'Anguilla'],
  ['http://sws.geonames.org/783754/', 'Albania'],
  ['http://sws.geonames.org/174982/', 'Armenia'],
  ['http://sws.geonames.org/3351879/', 'Angola'],
  ['http://sws.geonames.org/6697173/', 'Antarctica'],
  ['http://sws.geonames.org/3865483/', 'Argentina'],
  ['http://sws.geonames.org/5880801/', 'American Samoa'],
  ['http://sws.geonames.org/2782113/', 'Austria'],
  ['http://sws.geonames.org/2077456/', 'Australia'],
  ['http://sws.geonames.org/3577279/', 'Aruba'],
  ['http://sws.geonames.org/661882/', 'Aland Islands'],
  ['http://sws.geonames.org/587116/', 'Azerbaijan'],
  ['http://sws.geonames.org/3277605/', 'Bosnia and Herzegovina'],
  ['http://sws.geonames.org/3374084/', 'Barbados'],
  ['http://sws.geonames.org/1210997/', 'Bangladesh'],
  ['http://sws.geonames.org/2802361/', 'Belgium'],
  ['http://sws.geonames.org/2361809/', 'Burkina Faso'],
  ['http://sws.geonames.org/732800/', 'Bulgaria'],
  ['http://sws.geonames.org/290291/', 'Bahrain'],
  ['http://sws.geonames.org/433561/', 'Burundi'],
  ['http://sws.geonames.org/2395170/', 'Benin'],
  ['http://sws.geonames.org/3578476/', 'Saint Barthelemy'],
  ['http://sws.geonames.org/3573345/', 'Bermuda'],
  ['http://sws.geonames.org/1820814/', 'Brunei'],
  ['http://sws.geonames.org/3923057/', 'Bolivia'],
  ['http://sws.geonames.org/7626844/', 'Bonaire, Saint Eustatius and Saba '],
  ['http://sws.geonames.org/3469034/', 'Brazil'],
  ['http://sws.geonames.org/3572887/', 'Bahamas'],
  ['http://sws.geonames.org/1252634/', 'Bhutan'],
  ['http://sws.geonames.org/3371123/', 'Bouvet Island'],
  ['http://sws.geonames.org/933860/', 'Botswana'],
  ['http://sws.geonames.org/630336/', 'Belarus'],
  ['http://sws.geonames.org/3582678/', 'Belize'],
  ['http://sws.geonames.org/6251999/', 'Canada'],
  ['http://sws.geonames.org/1547376/', 'Cocos Islands'],
  ['http://sws.geonames.org/203312/', 'Democratic Republic of the Congo'],
  ['http://sws.geonames.org/239880/', 'Central African Republic'],
  ['http://sws.geonames.org/2260494/', 'Republic of the Congo'],
  ['http://sws.geonames.org/2658434/', 'Switzerland'],
  ['http://sws.geonames.org/2287781/', 'Ivory Coast'],
  ['http://sws.geonames.org/1899402/', 'Cook Islands'],
  ['http://sws.geonames.org/3895114/', 'Chile'],
  ['http://sws.geonames.org/2233387/', 'Cameroon'],
  ['http://sws.geonames.org/1814991/', 'China'],
  ['http://sws.geonames.org/3686110/', 'Colombia'],
  ['http://sws.geonames.org/3624060/', 'Costa Rica'],
  ['http://sws.geonames.org/3562981/', 'Cuba'],
  ['http://sws.geonames.org/3374766/', 'Cape Verde'],
  ['http://sws.geonames.org/7626836/', 'Curacao'],
  ['http://sws.geonames.org/2078138/', 'Christmas Island'],
  ['http://sws.geonames.org/146669/', 'Cyprus'],
  ['http://sws.geonames.org/3077311/', 'Czech Republic'],
  ['http://sws.geonames.org/2921044/', 'Germany'],
  ['http://sws.geonames.org/223816/', 'Djibouti'],
  ['http://sws.geonames.org/2623032/', 'Denmark'],
  ['http://sws.geonames.org/3575830/', 'Dominica'],
  ['http://sws.geonames.org/3508796/', 'Dominican Republic'],
  ['http://sws.geonames.org/2589581/', 'Algeria'],
  ['http://sws.geonames.org/3658394/', 'Ecuador'],
  ['http://sws.geonames.org/453733/', 'Estonia'],
  ['http://sws.geonames.org/357994/', 'Egypt'],
  ['http://sws.geonames.org/2461445/', 'Western Sahara'],
  ['http://sws.geonames.org/338010/', 'Eritrea'],
  ['http://sws.geonames.org/2510769/', 'Spain'],
  ['http://sws.geonames.org/337996/', 'Ethiopia'],
  ['http://sws.geonames.org/660013/', 'Finland'],
  ['http://sws.geonames.org/2205218/', 'Fiji'],
  ['http://sws.geonames.org/3474414/', 'Falkland Islands'],
  ['http://sws.geonames.org/2081918/', 'Micronesia'],
  ['http://sws.geonames.org/2622320/', 'Faroe Islands'],
  ['http://sws.geonames.org/3017382/', 'France'],
  ['http://sws.geonames.org/2400553/', 'Gabon'],
  ['http://sws.geonames.org/2635167/', 'United Kingdom'],
  ['http://sws.geonames.org/3580239/', 'Grenada'],
  ['http://sws.geonames.org/614540/', 'Georgia'],
  ['http://sws.geonames.org/3381670/', 'French Guiana'],
  ['http://sws.geonames.org/3042362/', 'Guernsey'],
  ['http://sws.geonames.org/2300660/', 'Ghana'],
  ['http://sws.geonames.org/2411586/', 'Gibraltar'],
  ['http://sws.geonames.org/3425505/', 'Greenland'],
  ['http://sws.geonames.org/2413451/', 'Gambia'],
  ['http://sws.geonames.org/2420477/', 'Guinea'],
  ['http://sws.geonames.org/3579143/', 'Guadeloupe'],
  ['http://sws.geonames.org/2309096/', 'Equatorial Guinea'],
  ['http://sws.geonames.org/390903/', 'Greece'],
  ['http://sws.geonames.org/3474415/', 'South Georgia and the South Sandwich Islands'],
  ['http://sws.geonames.org/3595528/', 'Guatemala'],
  ['http://sws.geonames.org/4043988/', 'Guam'],
  ['http://sws.geonames.org/2372248/', 'Guinea-Bissau'],
  ['http://sws.geonames.org/3378535/', 'Guyana'],
  ['http://sws.geonames.org/1819730/', 'Hong Kong'],
  ['http://sws.geonames.org/1547314/', 'Heard Island and McDonald Islands'],
  ['http://sws.geonames.org/3608932/', 'Honduras'],
  ['http://sws.geonames.org/3202326/', 'Croatia'],
  ['http://sws.geonames.org/3723988/', 'Haiti'],
  ['http://sws.geonames.org/719819/', 'Hungary'],
  ['http://sws.geonames.org/1643084/', 'Indonesia'],
  ['http://sws.geonames.org/2963597/', 'Ireland'],
  ['http://sws.geonames.org/294640/', 'Israel'],
  ['http://sws.geonames.org/3042225/', 'Isle of Man'],
  ['http://sws.geonames.org/1269750/', 'India'],
  ['http://sws.geonames.org/1282588/', 'British Indian Ocean Territory'],
  ['http://sws.geonames.org/99237/', 'Iraq'],
  ['http://sws.geonames.org/130758/', 'Iran'],
  ['http://sws.geonames.org/2629691/', 'Iceland'],
  ['http://sws.geonames.org/3175395/', 'Italy'],
  ['http://sws.geonames.org/3042142/', 'Jersey'],
  ['http://sws.geonames.org/3489940/', 'Jamaica'],
  ['http://sws.geonames.org/248816/', 'Jordan'],
  ['http://sws.geonames.org/1861060/', 'Japan'],
  ['http://sws.geonames.org/192950/', 'Kenya'],
  ['http://sws.geonames.org/1527747/', 'Kyrgyzstan'],
  ['http://sws.geonames.org/1831722/', 'Cambodia'],
  ['http://sws.geonames.org/4030945/', 'Kiribati'],
  ['http://sws.geonames.org/921929/', 'Comoros'],
  ['http://sws.geonames.org/3575174/', 'Saint Kitts and Nevis'],
  ['http://sws.geonames.org/1873107/', 'North Korea'],
  ['http://sws.geonames.org/1835841/', 'South Korea'],
  ['http://sws.geonames.org/831053/', 'Kosovo'],
  ['http://sws.geonames.org/285570/', 'Kuwait'],
  ['http://sws.geonames.org/3580718/', 'Cayman Islands'],
  ['http://sws.geonames.org/1522867/', 'Kazakhstan'],
  ['http://sws.geonames.org/1655842/', 'Laos'],
  ['http://sws.geonames.org/272103/', 'Lebanon'],
  ['http://sws.geonames.org/3576468/', 'Saint Lucia'],
  ['http://sws.geonames.org/3042058/', 'Liechtenstein'],
  ['http://sws.geonames.org/1227603/', 'Sri Lanka'],
  ['http://sws.geonames.org/2275384/', 'Liberia'],
  ['http://sws.geonames.org/932692/', 'Lesotho'],
  ['http://sws.geonames.org/597427/', 'Lithuania'],
  ['http://sws.geonames.org/2960313/', 'Luxembourg'],
  ['http://sws.geonames.org/458258/', 'Latvia'],
  ['http://sws.geonames.org/2215636/', 'Libya'],
  ['http://sws.geonames.org/2542007/', 'Morocco'],
  ['http://sws.geonames.org/2993457/', 'Monaco'],
  ['http://sws.geonames.org/617790/', 'Moldova'],
  ['http://sws.geonames.org/3194884/', 'Montenegro'],
  ['http://sws.geonames.org/3578421/', 'Saint Martin'],
  ['http://sws.geonames.org/1062947/', 'Madagascar'],
  ['http://sws.geonames.org/2080185/', 'Marshall Islands'],
  ['http://sws.geonames.org/718075/', 'Macedonia'],
  ['http://sws.geonames.org/2453866/', 'Mali'],
  ['http://sws.geonames.org/1327865/', 'Myanmar'],
  ['http://sws.geonames.org/2029969/', 'Mongolia'],
  ['http://sws.geonames.org/1821275/', 'Macao'],
  ['http://sws.geonames.org/4041468/', 'Northern Mariana Islands'],
  ['http://sws.geonames.org/3570311/', 'Martinique'],
  ['http://sws.geonames.org/2378080/', 'Mauritania'],
  ['http://sws.geonames.org/3578097/', 'Montserrat'],
  ['http://sws.geonames.org/2562770/', 'Malta'],
  ['http://sws.geonames.org/934292/', 'Mauritius'],
  ['http://sws.geonames.org/1282028/', 'Maldives'],
  ['http://sws.geonames.org/927384/', 'Malawi'],
  ['http://sws.geonames.org/3996063/', 'Mexico'],
  ['http://sws.geonames.org/1733045/', 'Malaysia'],
  ['http://sws.geonames.org/1036973/', 'Mozambique'],
  ['http://sws.geonames.org/3355338/', 'Namibia'],
  ['http://sws.geonames.org/2139685/', 'New Caledonia'],
  ['http://sws.geonames.org/2440476/', 'Niger'],
  ['http://sws.geonames.org/2155115/', 'Norfolk Island'],
  ['http://sws.geonames.org/2328926/', 'Nigeria'],
  ['http://sws.geonames.org/3617476/', 'Nicaragua'],
  ['http://sws.geonames.org/2750405/', 'Netherlands'],
  ['http://sws.geonames.org/3144096/', 'Norway'],
  ['http://sws.geonames.org/1282988/', 'Nepal'],
  ['http://sws.geonames.org/2110425/', 'Nauru'],
  ['http://sws.geonames.org/4036232/', 'Niue'],
  ['http://sws.geonames.org/2186224/', 'New Zealand'],
  ['http://sws.geonames.org/286963/', 'Oman'],
  ['http://sws.geonames.org/3703430/', 'Panama'],
  ['http://sws.geonames.org/3932488/', 'Peru'],
  ['http://sws.geonames.org/4030656/', 'French Polynesia'],
  ['http://sws.geonames.org/2088628/', 'Papua New Guinea'],
  ['http://sws.geonames.org/1694008/', 'Philippines'],
  ['http://sws.geonames.org/1168579/', 'Pakistan'],
  ['http://sws.geonames.org/798544/', 'Poland'],
  ['http://sws.geonames.org/3424932/', 'Saint Pierre and Miquelon'],
  ['http://sws.geonames.org/4030699/', 'Pitcairn'],
  ['http://sws.geonames.org/4566966/', 'Puerto Rico'],
  ['http://sws.geonames.org/6254930/', 'Palestinian Territory'],
  ['http://sws.geonames.org/2264397/', 'Portugal'],
  ['http://sws.geonames.org/1559582/', 'Palau'],
  ['http://sws.geonames.org/3437598/', 'Paraguay'],
  ['http://sws.geonames.org/289688/', 'Qatar'],
  ['http://sws.geonames.org/935317/', 'Reunion'],
  ['http://sws.geonames.org/798549/', 'Romania'],
  ['http://sws.geonames.org/6290252/', 'Serbia'],
  ['http://sws.geonames.org/2017370/', 'Russia'],
  ['http://sws.geonames.org/49518/', 'Rwanda'],
  ['http://sws.geonames.org/102358/', 'Saudi Arabia'],
  ['http://sws.geonames.org/2103350/', 'Solomon Islands'],
  ['http://sws.geonames.org/241170/', 'Seychelles'],
  ['http://sws.geonames.org/366755/', 'Sudan'],
  ['http://sws.geonames.org/7909807/', 'South Sudan'],
  ['http://sws.geonames.org/2661886/', 'Sweden'],
  ['http://sws.geonames.org/1880251/', 'Singapore'],
  ['http://sws.geonames.org/3370751/', 'Saint Helena'],
  ['http://sws.geonames.org/3190538/', 'Slovenia'],
  ['http://sws.geonames.org/607072/', 'Svalbard and Jan Mayen'],
  ['http://sws.geonames.org/3057568/', 'Slovakia'],
  ['http://sws.geonames.org/2403846/', 'Sierra Leone'],
  ['http://sws.geonames.org/3168068/', 'San Marino'],
  ['http://sws.geonames.org/2245662/', 'Senegal'],
  ['http://sws.geonames.org/51537/', 'Somalia'],
  ['http://sws.geonames.org/3382998/', 'Suriname'],
  ['http://sws.geonames.org/2410758/', 'Sao Tome and Principe'],
  ['http://sws.geonames.org/3585968/', 'El Salvador'],
  ['http://sws.geonames.org/7609695/', 'Sint Maarten'],
  ['http://sws.geonames.org/163843/', 'Syria'],
  ['http://sws.geonames.org/934841/', 'Swaziland'],
  ['http://sws.geonames.org/3576916/', 'Turks and Caicos Islands'],
  ['http://sws.geonames.org/2434508/', 'Chad'],
  ['http://sws.geonames.org/1546748/', 'French Southern Territories'],
  ['http://sws.geonames.org/2363686/', 'Togo'],
  ['http://sws.geonames.org/1605651/', 'Thailand'],
  ['http://sws.geonames.org/1220409/', 'Tajikistan'],
  ['http://sws.geonames.org/4031074/', 'Tokelau'],
  ['http://sws.geonames.org/1966436/', 'East Timor'],
  ['http://sws.geonames.org/1218197/', 'Turkmenistan'],
  ['http://sws.geonames.org/2464461/', 'Tunisia'],
  ['http://sws.geonames.org/4032283/', 'Tonga'],
  ['http://sws.geonames.org/298795/', 'Turkey'],
  ['http://sws.geonames.org/3573591/', 'Trinidad and Tobago'],
  ['http://sws.geonames.org/2110297/', 'Tuvalu'],
  ['http://sws.geonames.org/1668284/', 'Taiwan'],
  ['http://sws.geonames.org/149590/', 'Tanzania'],
  ['http://sws.geonames.org/690791/', 'Ukraine'],
  ['http://sws.geonames.org/226074/', 'Uganda'],
  ['http://sws.geonames.org/5854968/', 'United States Minor Outlying Islands'],
  ['http://sws.geonames.org/6252001/', 'United States'],
  ['http://sws.geonames.org/3439705/', 'Uruguay'],
  ['http://sws.geonames.org/1512440/', 'Uzbekistan'],
  ['http://sws.geonames.org/3164670/', 'Vatican'],
  ['http://sws.geonames.org/3577815/', 'Saint Vincent and the Grenadines'],
  ['http://sws.geonames.org/3625428/', 'Venezuela'],
  ['http://sws.geonames.org/3577718/', 'British Virgin Islands'],
  ['http://sws.geonames.org/4796775/', 'U.S. Virgin Islands'],
  ['http://sws.geonames.org/1562822/', 'Vietnam'],
  ['http://sws.geonames.org/2134431/', 'Vanuatu'],
  ['http://sws.geonames.org/4034749/', 'Wallis and Futuna'],
  ['http://sws.geonames.org/4034894/', 'Samoa'],
  ['http://sws.geonames.org/69543/', 'Yemen'],
  ['http://sws.geonames.org/1024031/', 'Mayotte'],
  ['http://sws.geonames.org/953987/', 'South Africa'],
  ['http://sws.geonames.org/895949/', 'Zambia'],
  ['http://sws.geonames.org/878675/', 'Zimbabwe'],
  ['http://sws.geonames.org/8505033/', 'Serbia and Montenegro'],
  ['http://sws.geonames.org/8505032/', 'Netherlands Antilles']
];

const host = [
  [OPEX_PREFIX+'all_host', 'All Hosts'],
  [OPEX_PREFIX+'personal_device', 'Personal Device'],
  [OPEX_PREFIX+'personal_social_media_website','Personal Social Media Website'],
  [OPEX_PREFIX+'academic_website', 'Academic Website'],
  [OPEX_PREFIX+'non_commercial_website', 'Non Commercial Website'],
  [OPEX_PREFIX+'commercial_website', 'Commercial Website']
];

module.exports = {
  operators: operators,
  units: units,
  constraints: constraints,
  spatial: spatial,
  host: host,
  actions: actions,
  ID_PREFIX: ID_PREFIX,
  TEMP_ID_PREFIX: TEMP_ID_PREFIX,
  OP_PREFIX: OP_PREFIX,
  ODRL_PREFIX: ODRL_PREFIX,
  OPEX_PREFIX: OPEX_PREFIX,
  DCTERM_PREFIX: DCTERM_PREFIX
};
